######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

CFLAGS=-Os
CC=$(E_CC)
export CC CFLAGS

CONF:
	echo No configuration here
COMP:
	make all

CLEAN:
	make clean

INSTALL: FORCE
	install -D -m 755 force_ethpc_renew_ip $(E_DEST)/root/mtlk/etc/force_ethpc_renew_ip

STRIP:
	$(E_STRIP) $(E_DEST)/root/mtlk/etc/force_ethpc_renew_ip

FORCE:

	
