######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

CFLAGS=-Os -march=armv4 -msoft-float
LDFLAGS=$(E_LDFLAGS)
CC=$(E_CC)
export CC CFLAGS LDFLAGS

.PHONY: CONF COMP CLEAN INSTALL STRIP FORCE

CONF:
	@echo "No configuration needed"
COMP:
	$(MAKE) all

CLEAN:
	$(MAKE) clean

INSTALL: FORCE
	install -D -m 755 hnap_wps_status_monitor $(E_DEST)/root/mtlk/etc/hnap_wps_status_monitor

STRIP:
	$(E_STRIP) $(E_DEST)/root/mtlk/etc/hnap_wps_status_monitor

FORCE:

	
