ip_config_method = 0
BridgeMode = 4
HostName = WAP610N
ip_lan = 192.168.1.1
subnet_lan = 255.255.255.0
default_gw = 192.168.1.1
DHCPDEnabled = 0
DHCPDStartAddress = 192.168.1.10
DHCPDEndAddress = 192.168.1.20
DHCPDSubnet = 255.255.255.0
DHCPDWINS = 192.168.1.1
DHCPDDomain = Local
DHCPDLeaseTime = 864000
LoopBreakingEnabled = 0
auto_network_type = 0
AdminUserName = admin
AdminPassword = admin
AuthenticationTimeout = 600
DeviceName = WAP610N
VendorName = Cisco-Linksys, LLC
ModelName = Wireless-N Access Point with Dual-Band
ModelDescription = Wireless-N Access Point with Dual-Band
FirmwareVersion = v1.0.08
Language = EN
SSH_Enabled = 1
Telnet_Enabled = 1
