#!/bin/sh
# A pushbutton daemon for dorango
# Hardware Safe-Shutdown button monitor daemon for WAP610N

# The monitor can be started by both early boot and WPS initialization.
# Use an atomic directory lock so only one process reads the GPIO device.
WPS_MONITOR_LOCK=/tmp/WPS_PBC_monitor.lock
if ! mkdir "$WPS_MONITOR_LOCK" 2>/dev/null; then
	exit 0
fi
trap 'rmdir "$WPS_MONITOR_LOCK" 2>/dev/null' 0 1 2 15

# Wait for /tmp/HW.ini to be generated by the wireless initialization.
# The file can appear after the early boot script starts.
for i in 1 2 3 4 5 6 7 8 9 10; do
	[ -f /tmp/HW.ini ] && break
	sleep 1
done

WPS_PBC_GPIO=`awk -F "=" '/^WPS_PB/ {str = $2; gsub(/ /, "", str); sub(/\r/, "", str); print str}' /tmp/HW.ini 2>/dev/null`

# Some board configuration files store the GPIO as a number instead of a
# device path. Normalize it before testing the device.
case "$WPS_PBC_GPIO" in
	''|null)
		;;
	*[!0-9]*)
		;;
	*)
		WPS_PBC_GPIO="/dev/gpio$WPS_PBC_GPIO"
		;;
esac

if [ -z "$WPS_PBC_GPIO" ] || [ "$WPS_PBC_GPIO" = "null" ]; then
	for g in /dev/gpio3 /dev/gpio13 /dev/gpio10 /dev/gpio1 /dev/gpio0 /dev/gpio14; do
		if [ -e "$g" ]; then
			WPS_PBC_GPIO="$g"
			break
		fi
	done
fi

if [ -n "$WPS_PBC_GPIO" ] && [ -e "$WPS_PBC_GPIO" ]; then
	echo "--> [Hardware Daemon] WPS Safe-Shutdown Monitor started on $WPS_PBC_GPIO" > /dev/console
	while true
	do
		# Wait for physical WPS button press
		cat $WPS_PBC_GPIO > /dev/null
		echo "[HARDWARE EVENT] WPS Button Pressed! Executing Safe System Shutdown..." > /dev/console
		
		# Turn off activity LEDs
		echo 0 > /dev/led0 2>/dev/null || true
		echo 0 > /dev/led1 2>/dev/null || true
		
		# Sync storage buffers and safely halt CPU
		sync
		poweroff
	done
else
	echo "WPS pushbutton: not active (GPIO device not found)" > /dev/console
fi
