ctrl_interface=/var/run/wpa_supplicant
eapol_version=1
ap_scan=1
network={
	ssid="WscSecureAP"
	key_mgmt=WPA-PSK
	proto=WPA
	pairwise=TKIP
	psk=4064d4a999f4f94e078952f838b93a4071aa6e91c8a3fddf518ede4de2c5ac90
	scan_ssid=1
}
