######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######## Standard header end ##############

#include ../Makefile.MTLK.vars

CC=$(E_CC)
LD=$(E_LD)
CFLAGS=$(E_CFLAGS)
LDFLAGS=$(E_LDFLAGS)

CFLAGS+=-I. -Os -march=armv4 -msoft-float -Wall -DSTANDALONE

OBJS=get_env_param.o
TARGET=get_env_param

.PHONY: CONF COMP CLEAN INSTALL STRIP FORCE

CONF:
	@echo "No config needed here"

COMP: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) $(LDFLAGS)

CLEAN:
	rm -f *.o get_env_param

INSTALL: FORCE
	install -m 755 -D $(TARGET) $(E_DEST)/bin/$(TARGET)
STRIP: FORCE
	$(E_STRIP) $(E_DEST)/bin/$(TARGET)

FORCE:

%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

