######## Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######## Standard header end ##############

CC=$(E_CC)

#CC = arm-linux-gcc
#PATH := $(PATH):/opt/star/tools/arm-uclibc-3.4.6/bin
###CFLAGS = -fno-common -fno-builtin -Wall  -Dlinux -D__linux__ -Dunix

PLATFORM_CFLAGS = -Os -march=$(E_ARCH) -msoft-float
INCLUDE=$(E_INCLUDE)
LIBPATH=$(E_LDFLAGS) 
LIB=$(E_LDFLAGS)

export

# DO NOT DELETE THIS LINE -- mkdep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.

CONF:

COMP: all

CLEAN: clean

INSTALL: FORCE
	install -m 755 -D webs $(E_DEST)/root/mtlk/web/webs
STRIP: FORCE
	$(E_STRIP) $(E_DEST)/root/mtlk/web/webs

FORCE:

include Makefile

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
