#
# Copyright (c) 2006-2007 Metalink Broadband (Israel)
#
# @file    Makefile.440epx
#
# @brief   This file for AMCC PPC440EPx to build the wpa_supplicant utility
#
# Author:  Oleksandr Baglei <OleksandrB@metalinkbb.com>
#

CROSS_COMPILE=/opt/toolchains/amcc/toolchain/usr/bin/ppc_4xxFP-
CFLAGS=-O2
CC=${CROSS_COMPILE}gcc
STRIP=${CROSS_COMPILE}strip
export CC STRIP CFLAGS 

all:
	make

clean:
	make clean

