#
# Copyright (c) 2006-2007 Metalink Broadband (Israel)
#
# @file    Makefile.str9102
#
# @brief   This file for STAR 9102 Dorado to build the wpa_supplicant utility
#
# Author:  Oleksandr Baglei <OleksandrB@metalinkbb.com>
#

CROSS_COMPILE=/opt/toolchains/star/toolchain/tools/arm-uclibc-3.4.6/bin/arm-linux-uclibc-
CFLAGS=-Os
CC=${CROSS_COMPILE}gcc
STRIP=${CROSS_COMPILE}strip
export CC STRIP CFLAGS

all:
	make

clean:
	make clean

