ctrl_interface=/var/run/wpa_supplicant
eapol_version=1
ap_scan=1
network={
	ssid="eladd"
	key_mgmt=WPA-PSK
	proto=WPA
	pairwise=TKIP
	psk=C37844A77F463D59AF2D2E7FEC6D014E8FE5E510674F2AE56447DD443A147666
	scan_ssid=1
}
