######### Metalink (c) #####################
# Copyright (c) 2008,2009 Metalink Ltd.
# This file is distributed under the OpenSSL dual licenses.
# (BSD style open source licenses)
# See LICENSE file for more details.
######### Standard header begin ############

ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

#STAGING_DIR=/opt/star/tools/arm-uclibc-3.4.6
#PATH=$(STAGING_DIR)/bin:/bin:/sbin:/usr/bin:/usr/sbin
ARCH=arm
CC=$(E_CC)
CFLAGS += "-DOPENSSL_NO_KRB5 -DOPENSSL_NO_IDEA -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -Os -DSTRIP_UNUSED"
PATH=$(E_CROSS)/bin:/bin:/sbin:/usr/bin:/usr/sbin
export PATH ARCH CC CFLAGS

CONF:
	./Configure linux-$(ARCH) --prefix=/ --install_prefix=${TOPDIR}/openssl-lib \
         --openssldir=/usr/lib/ssl -L$(E_CROSS)/lib -ldl \
         -I$(E_CROSS)/include $(OPENSSL_OPTS) no-threads \
         shared no-idea no-mdc2 no-rc5

COMP:
	make CC=$(CC) -f Makefile all build-shared

CLEAN:
	make -f Makefile clean

INSTALL: FORCE
	install -m 777 -d  $(E_DEST)/lib/
	install -m 755 libcrypto.so* $(E_DEST)/lib/
	install -m 755 libssl.so* $(E_DEST)/lib/

STRIP:
	$(E_STRIP) $(E_DEST)/lib/libcrypto.so.0.*  $(E_DEST)/lib/libssl.so.0.*

FORCE:
