######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars

ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

.PHONY: CONF COMP CLEAN INSTALL STRIP FORCE
 
CONF:
	./configure --host=$(E_HOST) --with-cc=$(E_CC) --with-linker=$(E_LD) CFLAGS=$(E_CFLAGS) LDFLAGS=$(E_LDFLAGS) --disable-tls --disable-nls --disable-e2initrd-helper --prefix=$(E_DEST)

COMP:
	$(MAKE) -f Makefile libs

CLEAN:
	$(MAKE) -f Makefile clean

INSTALL: FORCE
	install -m 755 lib/uuid/libuuid.a $(E_DEST)/lib/libuuid.a
STRIP: FORCE
	$(E_STRIP) --strip-debug $(E_DEST)/lib/libuuid.a || true

FORCE:
	
#include Makefile
