^AdminUserName = admin
^AdminPassword = admin
^AuthenticationTimeout = 600
DeviceName = WAP610N
HostName = WAP610N
VendorName = Cisco-Linksys, LLC
ModelName = Wireless-N Access Point with Dual-Band
ModelDescription = Wireless-N Access Point with Dual-Band
FirmwareVersion = v1.0.08
Language = EN
