#
# Copyright (c) 2006-2007 Metalink Broadband (Israel)
#
# @file    Makefile.str9102
#
# @brief   This file for STAR 9102 Dorado to build the crc utility
#
# Author:  Oleksandr Baglei <OleksandrB@metalinkbb.com>
#

CROSS_COMPILE=/opt/star/tools/arm-uclibc-3.4.6/bin/arm-linux-uclibc-
CFLAGS=-Os
CC=${CROSS_COMPILE}gcc
export CC CFLAGS 

all:
	make

clean:
	make clean

