######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

STRIP:

CLEAN:

COMP:
	echo no compilation here

CONF:
	echo no configuration here

INSTALL: FORCE
	install -D -m 755 WPS_PBC.sh $(E_DEST)/root/mtlk/etc/WPS_PBC.sh
	install -D -m 755 etherdump_awk $(E_DEST)/root/mtlk/etc/etherdump_awk
	install -D -m 755 mtlk_init_daemons.sh $(E_DEST)/root/mtlk/etc/mtlk_init_daemons.sh
	install -D -m 755 mtlk_init_download_wls.sh $(E_DEST)/root/mtlk/etc/mtlk_init_download_wls.sh
	install -D -m 755 mtlk_init_ip.sh $(E_DEST)/root/mtlk/etc/mtlk_init_ip.sh
	install -D -m 755 mtlk_init_platform.sh.platform.$(PLATFORM_SUFFIX) $(E_DEST)/root/mtlk/etc/mtlk_init_platform.sh
	install -D -m 755 mtlk_init_rd.sh $(E_DEST)/root/mtlk/etc/mtlk_init_rd.sh
	install -D -m 755 mtlk_init_route.sh $(E_DEST)/root/mtlk/etc/mtlk_init_route.sh
	install -D -m 755 mtlk_init.sh $(E_DEST)/root/mtlk/etc/mtlk_init.sh
	install -D -m 755 mtlk_restore_defaults.sh $(E_DEST)/root/mtlk/etc/mtlk_restore_defaults.sh
	install -D -m 755 mtlk_save_log.sh $(E_DEST)/root/mtlk/etc/mtlk_save_log.sh

FORCE:
