
^AdminUserName = admin
^AdminPassword = admin
^AuthenticationTimeout = 600
DeviceName = WET610N
VendorName = Cisco-Linksys, LLC
ModelName = Wireless-N Ethernet Bridge with Dual-Band
ModelDescription = Wireless-N Ethernet Bridge with Dual-Band
FirmwareVersion = VB01.23
Language = EN

