######### Metalink (c) #####################
######### Standard header begin ############

## TOPDIR may be set. It points to the top directory where all the E_* variables are in Makefiles.MTLK.vars
ifdef E_TOPDIR
include $(E_TOPDIR)/scripts/Makefile.MTLK.vars
else
$(error "E_TOPDIR doesn't defined")
endif

######### Standard header end ##############

CCFLAGS=-O2 -march=$(E_ARCH) -msoft-float 
LIBS=
CC=$(E_CC)
STRIP=$(E_STRIP)
TARGET=vconfig
export CC STRIP CCFLAGS TARGET

.PHONY: CONF COMP CLEAN INSTALL STRIP FORCE

COMP:
	$(MAKE) CC=$(E_CC) STRIP=$(E_STRIP) CCFLAGS="-O2 -march=armv4 -D_GNU_SOURCE -Wall -msoft-float -I$(E_KERNEL)/include"

CLEAN:
	$(MAKE) clean

INSTALL: FORCE
	install -m 755 -D $(TARGET) $(E_DEST)/bin/$(TARGET)
	install -m 755 -D $(E_KERNEL)/net/8021q/8021q.ko $(E_DEST)/lib/modules/2.6.16-star/net/8021q.ko 

CONF:

STRIP:

FORCE:
